# Generated by Django 3.2.9 on 2021-12-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_id',
        ),
    ]
